---
namespace: merizrizal
name: utils
version: 1.0.0
readme: README.md
authors:
  - merizrizal@gmail.com

description: Utility for deployment

repository: https://github.com/merizrizal/ansible_collections_for_utilities
build_ignore: []
